# Generated by Django 4.0.3 on 2022-03-20 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnSeparator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Column Separator',
                'verbose_name_plural': 'Column Separators',
            },
        ),
        migrations.CreateModel(
            name='DataSetStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('has_range', models.BooleanField(default=False, help_text='use this option if data type has range')),
                ('default_content', models.CharField(max_length=1000)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Data Type',
                'verbose_name_plural': 'Data Types',
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('column_separator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.columnseparator')),
            ],
            options={
                'verbose_name': 'Schema',
                'verbose_name_plural': 'Schemas',
            },
        ),
        migrations.CreateModel(
            name='StringCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'String Character',
                'verbose_name_plural': 'String Characters',
            },
        ),
        migrations.CreateModel(
            name='SchemaRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('range_start', models.IntegerField(blank=True, null=True)),
                ('range_end', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.datatype')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.schema')),
            ],
            options={
                'verbose_name': 'Schema Row',
                'verbose_name_plural': 'Schema Rows',
            },
        ),
        migrations.AddField(
            model_name='schema',
            name='string_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.stringcharacter'),
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('csv_file', models.FileField(null=True, upload_to='csv_datasets/')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.schema')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.datasetstatus')),
            ],
            options={
                'verbose_name': 'Data set',
                'verbose_name_plural': 'Data sets',
            },
        ),
    ]
