# Generated by Django 4.0.3 on 2022-03-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_alter_dataset_csv_file_alter_schemarow_range_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemarow',
            name='range_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schemarow',
            name='range_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
